// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`
interface CloudflareEnv {
//  MY_KV_1: KVNamespace;
  R2_BUCKET: R2Bucket;
//  MY_DO: DurableObjectNamespace;
}
