import NavBar from "@/app/components/navbar"
import { AuthProvider } from "@/app/contexts/auth"
import type { Metadata } from "next"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50">
        <AuthProvider>
          <NavBar />
          <main className="p-8">{children}</main>
        </AuthProvider>
      </body>
    </html>
  )
}
